---
- hosts: all
  gather_facts: true

  vars:
    machinomy_contracts_path: '~/machinomy-contacts'
    ynos_path: '~/ynos'
    staging_path: '~/staging'

  tasks:
    - name: machinomy
      git:
        repo: https://github.com/machinomy/machinomy-contracts
        dest: "{{ machinomy_contracts_path }}"
        force: yes
        update: yes
        accept_hostkey: yes

    - command: yarn install
      args:
        chdir: "{{ machinomy_contracts_path }}"


 